# Generated by Django 3.2.5 on 2021-10-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, default='uploads/books/default.png', null=True, upload_to='uploads/book_image/%Y%m%d/'),
        ),
    ]
