# Generated by Django 3.1.7 on 2021-04-04 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210404_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='books.book'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('.5', '.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='1', max_length=3),
        ),
        migrations.CreateModel(
            name='Late_return_charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_days', models.IntegerField(default=0, max_length=100)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='books.borrower')),
            ],
        ),
    ]
